# Generated by Django 3.2.7 on 2021-09-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('escorrecta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='JuegoPreguntas.categoria')),
                ('premio', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='JuegoPreguntas.premio')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('puntos', models.IntegerField()),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='JuegoPreguntas.categoria')),
                ('opciones', models.ManyToManyField(related_name='opciones', to='JuegoPreguntas.Opcion')),
            ],
        ),
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('puntos', models.IntegerField(default=0)),
                ('premios', models.ManyToManyField(default=None, related_name='premios', to='JuegoPreguntas.Premio')),
            ],
        ),
    ]
