# Generated by Django 3.2.7 on 2021-09-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuegoPreguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ronda',
            name='premio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JuegoPreguntas.premio'),
        ),
    ]
